#!/usr/bin/python
import sys
import os

def usage():
	print "usage : bright number\nnumber : 1~15\n1 : Minimum, 15 : Maximum"
	sys.exit(1)

if len(sys.argv) != 2 :
	usage()

num = int(sys.argv[1])

if num > 15 or num < 1 :
	usage()

if os.getuid() != 0 :
	print "Execute as root"
	sys.exit(1)

hexnum = num * 0x11
st = str(hex(hexnum)).replace("0x", "")
os.system("setpci -s 00:02.0 F4.b=" + st)
